### PR TITLE
Add show logs to context menu of experiments running in the queue

### PR DESCRIPTION
**Pull request by mattseddon**
Part of https://github.com/iterative/vscode-dvc/issues/3178

WIP.

Lots of duplication in the PR that ~can~ will be removed. Need to think more about how to set this out so that it can be used under certain circumstances for things like `dvc pull`. Thinking maybe

1. show progress notification which contains "show logs" link
2. show logs link opens a terminal and starts piping the output in (like demo below)

### Demo

https://user-images.githubusercontent.com/37993418/221096848-df1e98c6-66c1-40e0-bb15-ae679d248c1f.mov

### CODE REVIEW

**Comment by mattseddon** [comment]
image

you got me

**Comment by dberenbaum** [comment]
@mattseddon Will it work for failed/successful experiments that were run by the queue also?

**Comment by shcheklein** [comment]
Looks great! Q: is there a way to control the Terminal name? To include the experiment name in it:

Screenshot 2023-02-24 at 10 22 04 AM

So that I can see the list of Tasks (experiments) / terminals like in this case ^^, switch between them, etc?

**Comment by mattseddon** [comment]
> @mattseddon Will it work for failed/successful experiments that were run by the queue also?

It can. Not sure if all of the required data is actually in `exp show` but I can work it out.

> Q: is there a way to control the Terminal name?

Yep, was getting there.

**Comment by mattseddon** [comment]
Need to refactor before I can get this in.

**Pull request closed without merging**
