### PR TITLE
Improve table styles

### PR DESCRIPTION
**Pull request by julieg18**
* add tooltips to row actions (checkbox and stars)
* take off first cell right border when the cell is sticky 
* increase workspace row height
* take off right border on the head rows last children
* update column resizer hover background color

## Demo

https://user-images.githubusercontent.com/43496356/187478759-e24444d3-0ca0-4404-8736-17707d784ad7.mov

Part of #2241

### CODE REVIEW

**Comment by mattseddon** [comment]
@julieg18 what happens at ~10 seconds of the video?

**Comment by julieg18** [comment]
> From watching the whole video I can assume that selecting the row removes the stickiness of the first column. This looks broken to me.

Yes, selecting the row turns off the stickiness. It's always been like that though (picture below was taken on the latest extension release):

image

Agreed though, it does look buggy... I can look into keeping selected rows sticky if we'd like!

**Comment by maxagin** [comment]
> Agreed though, it does look buggy... I can look into keeping selected rows sticky if we'd like!

Please share the updated version, when you have it. Thank you @julieg18

**Comment by maxagin** [comment]
Good work @julieg18 
Very minor: consistent vertical lines

Screen Shot 2022-08-29 at 9 26 03 PM

**Comment by maxagin** [comment]
In relation to the

> take off first cell right border when the cell is sticky

Screen Shot 2022-08-29 at 9 36 12 PM

**Comment by maxagin** [comment]
Just FYI. The selected first cell does not have a shadow:

Screen Shot 2022-08-29 at 9 39 16 PM

**Comment by maxagin** [comment]
Q: is the blue border when on hover 2px?

Screen Shot 2022-08-29 at 9 42 10 PM

**Comment by julieg18** [comment]
> Q: is the blue border when on hover 2px? 

Yes, it is 2px!

**Review by sroy3 — APPROVED** [review]
Since what was previously mentioned by Matt is out of scope. This LGTM! I would still follow up on it though.

**Comment by julieg18** [comment]
Ok, merged #2294 which fixed the none sticky selected rows issue! 

Also, per @maxagin comments, added opacity to the resizer bar and took off the borders when the header cells are sticky since those were both really simple fixes. Video is updated and I think we're good to merge once tests are passing!

**Comment by maxagin** [comment]
Looks like "The selected first cell does not have a shadow" also was fixed :) https://github.com/iterative/vscode-dvc/pull/2289#issuecomment-1231043608

**Pull request merged**
