### PR TITLE
Update copy around adding a new stage/defining a pipeline for a project without one

### PR DESCRIPTION
**Pull request by mattseddon**
Part of #4194

Took the basic step of updating the copy. Further changes will be required for #4222 as well and I think people will see this messaging even less.

### Screenshot

image

### CODE REVIEW

**Comment by shcheklein** [comment]
I think we still need to iterate on the copy. Some ideas:

1. Make button "Run experiment" (the same as all other Run button behave), and to avoid mental load with pipelines and stages
2. Change text to something more explicit. "To be able to run, queue, pass parameters, track data, etc- create a project file". Project file can be a link to `dvc.yaml`.

@dberenbaum @daavoo any other ideas on the copy here?

**Comment by mattseddon** [comment]
`Run experiment` is far less explicit than `Add Stage` as (unless I am mistaken) running experiments is not possible without having a stage.

I don't think we should be changing/inventing terms to try and reduce mental load. I may have missed one but I cannot find a single reference to "project file" relating to a `dvc.yaml` in the docs. If we are worried about introducing the pipeline term here then we should de-couple/remove this step from the table.

**Comment by shcheklein** [comment]
> Run experiment is far less explicit than Add Stage as (unless I am mistaken) running experiments is not possible without having a stage.

In this case the whole intention is to make experiments run, modify and run, etc to work. There is not intention at this stage to explain the benefits of the pipelines as is (cache intermediate artifacts), etc. Even the name pipeline, stage - etc -why should people bother about them at this page?

> I cannot find a single reference to "project file" relating to a dvc.yaml in the docs.

that's fine, we can make it "dvc.yaml" or Project `dvc.yaml` file, or configuration file ... something that comes from the basic user experience, not something new for them to lear

> If we are worried about introducing the pipeline term here then we should de-couple/remove this step from the table.

The whole intention of this step was not about introducing the pipelines, but about enabling all the experiments features in the extension. Please try to look at this from that angle. WDYT.

Again, curios about @dberenbaum and @daavoo 's take on this (since I see some benefits of using the pipelines term as well, just want to calibrate if I'm too biased into experiments).

**Comment by dberenbaum** [comment]
I'd like to find time to work on how we talk about pipelines and running experiments in the docs and then come back to this. Right now, I don't have a strong sense now of what's better and can see the pros and cons of both approaches. I'm also not sure yet that wording it one way or the other is going to make an impactful difference.

**Comment by shcheklein** [comment]
Let's try to make about experiments then please until we have more sense about the pipelines. To not confuse people with new terminology.

**Pull request merged**
