### PR TITLE
Rename "Timestamp" column label to "Created"

### PR DESCRIPTION
**Pull request by julieg18**
Renames the timestamp column's name to "Created", matching DVC CLI tables.

### Main: 
image

### PR:

image

Followup to [#2239 comment](https://github.com/iterative/vscode-dvc/pull/2239#discussion_r955448883)

### CODE REVIEW

**Review by sroy3 — APPROVED** [review]

**Comment by maxagin** [comment]
@julieg18, @shcheklein Shouldn't we request the DVC team change it since the Timestamp term is more efficient?

**Review by mattseddon — APPROVED** [review]

**Comment by mattseddon** [comment]
> @julieg18, @shcheklein Shouldn't we request the DVC team change it since the Timestamp term is more efficient?

"Timestamp" does not tell you what the timestamp represents. Created does.

**Comment by julieg18** [comment]
Going to go ahead and merge this! We can always revert if we decide that we want to keep the "Timestamp" name :)

**Comment by shcheklein** [comment]
@maxagin if we want to change this, let's raise an issue in the DVC repo first please. My take both are fine for now, there are pros and cons, so let's keep it at move forward.

**Comment by mattseddon** [comment]
> A timestamp is a digital record of the time of occurrence of a particular event.

Which event? When the experiment was created, when it was first modified, when it was last modified, when it was completed, last time it was selected?

**Comment by maxagin** [comment]
>A timestamp is a digital record of the time of occurrence of a particular event.

>>Which event? When the experiment was created, when it was first modified, when it was last modified, when it was completed, last time it was selected?

The entrance of the experiment.

---

Question. Why we do not display the following information in the table?

- Created
- First modified
- Last modified
- Completed
- Last time it was selected

**Pull request merged**
