### PR TITLE
Make the multiview template size dynamic for each plot inside

### PR DESCRIPTION
**Pull request by sroy3**
Prototype for #3757 

https://user-images.githubusercontent.com/3683420/234396857-3d7a21a0-393f-47a1-ab3c-3d355fb8f2c7.mov

This might actually work. This is better than I thought it would, probably because we already parse the template anyway at that time and calculation is straight forward as it had almost everything it needed.

There are some adjustments left, but this is just a prototype, I'll fix that in a secondary step. I first need to check if having multiple multi view plots would make this look laggy.

The one thing I don't like is the duplication of aspect ratios in the webview and the extension. If we change it some place, we'll forget to change at the other place. I'll try to make it so it's only in one place.

### CODE REVIEW

**Comment by sroy3** [comment]
https://user-images.githubusercontent.com/3683420/234596481-8da49421-ae98-4d06-9590-de63ff8eb959.mov

I'll need to add some debounce to the call to make this actually useful. Else it's going to move way too much.

**Comment by sroy3** [comment]
I don't think this is going to work after all. The problem is that when changing the template, we force the re-rendering of the React component. This will result in something very laggy, the more plots we have (especially with virtualized plots). The problem really is inside VegaLite and our templates were never the problem.  To fix this we need to fix it after VegaLite has created the component or fix it inside VegaLite directly.

See [video](https://drive.google.com/file/d/1pyjTDJZqapH1dgpFKxBGlt0HzEZ0fpjc/view?usp=share_link) (too big for GitHub)

**Comment by shcheklein** [comment]
> The problem is that when changing the template, we force the re-rendering of the React component. This will result in something very laggy, the more plots we have (especially with virtualized plots).

It's still better vs what we have now (not responding at all to resize). Even if it takes substantial amount of time to re-render. If that happens only when we change size- I think it's better to have something then.

> The problem really is inside VegaLite and our templates were never the proble

Let's create a ticket on their end to discuss it? How would you expect it to handle this? I think it would be great to describe / scope it.

**Comment by shcheklein** [comment]
>  To me, it does not feel like a great experience at all.

Yep. The way you are describing it it's not good indeed. What I struggle to understand why it's not possible to implement it with changing the template on the resize w/o these delays, etc, etc.

> I made a separate fix last week that is also seen in this PR (https://github.com/iterative/vscode-dvc/pull/3774), which probably helps in making this look better.

tbh, not sure I understand how the fix is related. Could you explain it please?

**Pull request closed without merging**
