### PR TITLE
Add authorize step to both PR workflows

### PR DESCRIPTION
**Pull request by mattseddon**
More information: https://github.com/iterative/cml/pull/574#issuecomment-1188650440

image

### Internal

image

### External

image

### CODE REVIEW

**Comment by shcheklein** [comment]
@0x2b3bfa0 hey, as an expert in this, could you please review and see that we are not missing anything and/or there are better ways to organize it now (run tests for external contributions after an approval).

**Comment by 0x2b3bfa0** [comment]
@mattseddon wrote me a Slack direct message a dozen hours ago asking the same. 👍🏼 

#### See also
* https://github.com/iterative/cml/pull/574#issuecomment-1188650440

**Review by 0x2b3bfa0 — COMMENTED** [review]
Looks good to me! 🎉

**Comment by mattseddon** [comment]
@0x2b3bfa0 shouldn't the checks be run when I open a PR?

**Comment by mattseddon** [comment]
> @0x2b3bfa0 shouldn't the checks be run when I open a PR?

Because the checks are run in the context of the base branch authorize is not available. See https://github.com/iterative/vscode-dvc/pull/2645 for when the checks do get run. Will need to merge this in two parts. With `on: pull_request` and then remove that trigger afterwards.

**Comment by mattseddon** [comment]
> Code Climate has analyzed commit [9c59ba3](https://github.com/iterative/vscode-dvc/commit/9c59ba33e3a05f37866d95b82df2b844396552b7) and detected **0 issues** on this pull request.
> 
> The test coverage on the diff in this pull request is **100.0%** (**85%** is the threshold).
> 
> This pull request will bring the total coverage in the repository to **96.8%** (**0.0%** change).
> 
> View more on [Code Climate](https://codeclimate.com/repos/608b5886f52398018b00264c/pull/2644).

This seems like a bug in 

The problem is here: https://github.com/paambaati/codeclimate-action/blob/main/src/main.ts#L38
The line needs to be extended to include `pull_request_target`

**Comment by mattseddon** [comment]
Raised https://github.com/paambaati/codeclimate-action/issues/627. This is blocked until that gets resolved.

**Comment by 0x2b3bfa0** [comment]
It's hacky, but you could use an `env` block to override those environment variables for the action.

**Comment by 0x2b3bfa0** [comment]
E.g.
```yaml
env:
  GITHUB_EVENT_NAME: ${{ github.event_name == 'pull_request_target' && 'pull_request' || github.event_name }}
```

**Comment by mattseddon** [comment]
> E.g.
> 
> ```yaml
>       - uses: paambaati/codeclimate-action@v3.1.1
>         env:
>           CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
>           GITHUB_EVENT_NAME: ${{ github.event_name == 'pull_request_target' && 'pull_request' || github.event_name }}
>         with:
>           coverageCommand: xvfb-run -a yarn run cover
>           coverageLocations: ${{github.workspace}}/coverage/lcov.info:lcov
> ```

It doesn't seem like overriding the environment variables like this has any effect on the action 😞.

**Pull request closed without merging**
