### PR TITLE
Language Server with Definitions Only

### PR DESCRIPTION
**Pull request by wolmir**
# Language server for data pipelines

This PR will introduce the language server module to the extension.

### Data Pipelines and dvc.yaml

[Data Pipelines](https://dvc.org/doc/start/data-management/data-pipelines)
[dvc.yaml](https://dvc.org/doc/user-guide/project-structure/dvcyaml-files)
[Pipelines](https://dvc.org/doc/user-guide/pipelines)
[Stage command](https://dvc.org/doc/command-reference/stage)
[Original issue](https://github.com/iterative/vscode-dvc/issues/1192)

### VSCode language support

[Language extensions](https://code.visualstudio.com/api/language-extensions/overview)
[Available language support list from VSCode with examples](https://code.visualstudio.com/api/language-extensions/programmatic-language-features)

### Language Servers

[Introduction](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide)
[Protocol Specification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/)
[The Framework to build one](https://github.com/microsoft/vscode-languageserver-node)
[Some extension samples](https://github.com/microsoft/vscode-extension-samples) (Look for the ones prefixed by `lsp-*`)

## Demo

The main purpose of this PR is to add the language server scaffolding to the extension project.
However, we also provided a small [Go to Definition](https://code.visualstudio.com/docs/editor/editingevolved#_go-to-definition) feature in order to add some value for the user and as an example of how to work in the server module.

The feature works inside strings of dvc.yaml files, and will provide a set of location where the symbols referenced in those strings are found inside a project.

https://user-images.githubusercontent.com/1231848/191082719-f3166fcd-c8b5-4ee3-bd9a-6bcad5c9acaa.mov

### CODE REVIEW

**Comment by wolmir** [comment]
@mattseddon @julieg18 @sroy3 

Can you guys skim this and compare with the original PR, please?

The definitions handler is the simplest one, and by removing the others it allowed me to skip that
DvcYaml model entirely.

Plus some other stuff could be removed, like the pythonFiles thing.
In total there were about -800 lines from the original, but I would really like your opinion here.
If they were both ready to go, would you rather merge this one or the original one?

**Review by sroy3 — APPROVED** [review]
This looks good to me. All my comments are in the other PR and are mostly for my curiosity, nothing major.

**Comment by mattseddon** [comment]
> @mattseddon @julieg18 @sroy3
> 
> Can you guys skim this and compare with the original PR, please?
> 
> The definitions handler is the simplest one, and by removing the others it allowed me to skip that DvcYaml model entirely.
> 
> Plus some other stuff could be removed, like the pythonFiles thing. In total there were about -800 lines from the original, but I would really like your opinion here. If they were both ready to go, would you rather merge this one or the original one?

@wolmir can you please put a demo and a description on the PR that you would like to be reviewed.

**Review by julieg18 — APPROVED** [review]
Looks good to me!

**Comment by julieg18** [comment]
> However, we also provided a small [Go to Definition](https://code.visualstudio.com/docs/editor/editingevolved#_go-to-definition) feature in order to add some value for the user and as an example of how to work in the server module.

Weird, the "Go to Definition" feature doesn't seem to be working on my end: 


https://user-images.githubusercontent.com/43496356/191131741-e59611a9-48b9-4237-b7bf-e151815360e5.mov

**Comment by mattseddon** [comment]
The language server is adding definitions in Python files (e.g on `re.sub`):

### With language server

https://user-images.githubusercontent.com/37993418/191136505-a56c08e3-7204-4616-b832-83fb6b18f8c7.mov

### Expected behaviour

https://user-images.githubusercontent.com/37993418/191136451-d5be9d46-e898-4748-a827-1abe36794bcb.mov


I would also expect that trying to "Go to definition" inside of the `dvc.yaml` file would open give the option to open individual files (e.g step into a python file). At least I would expect that the `cmd` line is split into its component parts and a definition be displayed only for the symbol that is clicked on (e.g for `data/features` not `cmd: ... data/features`). It also seems like for `example-get-started` you cannot go to the params file definitions:

https://user-images.githubusercontent.com/37993418/191136736-59acb67f-9d57-4353-bae4-7989d5ab58ac.mov

**Comment by wolmir** [comment]
This provider is way too simple to add any value, and even an implementation that satisfies the constraints Matt mentioned above is going to complicate the PR again and again

Can we leave the definitions for later as well, and keep only the server skeleton then?
So we have a chance of adding a solid definitions increment?

**Comment by wolmir** [comment]
> This provider is way too simple to add any value, and even an implementation that satisfies the constraints Matt mentioned above is going to complicate the PR again and again
> 
> Can we leave the definitions for later as well, and keep only the server skeleton then? So we have a chance of adding a solid definitions increment?

Actually, not really, I'm already fixing it and It's not that much more complicated.

Will update here shortly.

**Pull request merged**
