### PR TITLE
Update demo project and latest tested CLI version (2.49.0)

### PR DESCRIPTION
**Pull request by mattseddon**

### CODE REVIEW

**Review by sroy3 — APPROVED** [review]

**Review by julieg18 — APPROVED** [review]

**Comment by sroy3** [comment]
Hope you don't mind, I updated this PR to use the newest version instead of merging and creating a new PR.

**Comment by mattseddon** [comment]
> Hope you don't mind, I updated this PR to use the newest version instead of merging and creating a new PR.

Thank you. I can't remember if the conmit message or the title ends up in the changelog. We'll find out.

**Comment by sroy3** [comment]
> > Hope you don't mind, I updated this PR to use the newest version instead of merging and creating a new PR.
> 
> Thank you. I can't remember if the conmit message or the title ends up in the changelog. We'll find out.

You're right. It's the title. I'll start the release and change it in the changelog while it's fresh in mind.

**Comment by mattseddon** [comment]
No worries. Make that release now. I might make another one later anyway 🙏🏻.

**Pull request merged**
