### PR TITLE
Change the background color for the smooth slider over plots

### PR DESCRIPTION
**Pull request by stephr0y**
Following https://github.com/iterative/vscode-dvc/pull/3405#discussion_r1129926118

https://user-images.githubusercontent.com/3683420/223824128-725ff041-ecd0-43bd-963f-113c370240e9.mov

### CODE REVIEW

**Review by mattseddon — APPROVED** [review]

**Comment by mattseddon** [comment]
Up to you on whether or not to merge. Was a suggestion not a requirement.

**Comment by mattseddon** [comment]
Looks weird for zoomed-in plot 🤦🏻:

image

**Comment by sroy3** [comment]
> Looks weird for zoomed-in plot 🤦🏻:
> 
> image

Now (first) vs before (second) the change:

https://user-images.githubusercontent.com/3683420/224347047-fca93e3a-ac48-4aac-9695-dce52e19e734.mov

It looks like it's actually better most of the time. If we want to make it look better, we'd need something different completely. Let's leave it like this for now as it's an improvement, and change it when we think of something better.

**Comment by sroy3** [comment]
> I think the previous implementation was a bit better to be honest. I would try for these sliders to blend more with the plot itself. I don't see a strong reason for all sliders to have the same background, the context is different for them.
> 
> Sorry for going back and forth @sroy3 on this.

There are times when the slider is almost the same color as the background (see 0:42, 0:44, 0:48 in the video) (just making sure we're seeing the same thing). But I can easily revert and don't have an opinion on the matter.

**Comment by sroy3** [comment]
Revert in #3444. Feel free to merge if needed.

**Pull request merged**
