### PR TITLE
Disable Restyled.io bot

### LINKED ISSUE #1896: linter: inconsistent/wrong linting in local vs. CI envs
Local linting is enforced by a Git hook that runs `lint-staged` (a Yarn package &. command) directly. On the CI, the custom `lint` script is used which uses `turbo` instead. This seems to cause inconsistent results when linting on different envs, causing developer confusion.

- Local inconsistency example: https://github.com/iterative/vscode-dvc/issues/1881
- CI inconsistency (ongoing issue): https://github.com/iterative/vscode-dvc/pull/1889#pullrequestreview-1005342763

> So far I've only noticed this in Markdown files which is not a big deal I suppose, but I suspect that it can easily happen on the code base too.

### PR DESCRIPTION
**Pull request by mattseddon**
Closes #1896

Our linters are setup to run on pre-commit hooks and fail the pipeline if they find any issues. The PRs created by this bot are therefore false positives and/or create no value.

[Docs](https://github.com/restyled-io/restyled.io/wiki/Configuring-Restyled)

### CODE REVIEW

**Comment by mattseddon** [comment]
Got turned on when we made the repo public. It should just follow the prettier config but has some bugs.

**Comment by mattseddon** [comment]
I cannot disable any of the other ways: https://github.com/restyled-io/restyled.io/wiki/Disabling-Restyled

**Comment by mattseddon** [comment]
Done manually by @shcheklein

**Comment by jorgeorpinel** [comment]
> what's wrong with it

https://github.com/iterative/vscode-dvc/issues/1896

**Pull request closed without merging**
