### PR TITLE
Move plot legends to top (on zoom)

### PR DESCRIPTION
**Pull request by mattseddon**
Compliments #3228.

Related to https://github.com/iterative/vscode-dvc/issues/3226

### Demo

https://user-images.githubusercontent.com/37993418/216891284-55ee9552-21a1-428f-9858-26216aba6016.mov

### CODE REVIEW

**Comment by shcheklein** [comment]
Can we test it on 7 selected experiments? I'm worried that legend won't look good / can take too much space.

**Comment by mattseddon** [comment]
> Can we test it on 7 selected experiments? I'm worried that legend won't look good / can take too much space.

Screenshot 2023-02-06 at 6 56 17 pm

**Comment by mattseddon** [comment]
No longer like the change

**Comment by mattseddon** [comment]
Did test changing the direction to horizontal too:

image

**Pull request closed without merging**
