### PR TITLE
Add a copy button for comparison table rows

### PR DESCRIPTION
**Pull request by sroy3**
https://user-images.githubusercontent.com/3683420/185461084-45bc63fa-1a5d-4f51-8108-a836dbed42cb.mov

### CODE REVIEW

**Comment by shcheklein** [comment]
Thanks @sroy3 for taking care of this ... can we also make names "selectable" as a regular text?

**Comment by sroy3** [comment]
> Thanks @sroy3 for taking care of this ... can we also make names "selectable" as a regular text?
Just added. Might be a little annoying because it's a button that toggles the row, but it isn't a destructive action.
https://user-images.githubusercontent.com/3683420/185461757-e41bd5b6-e3ac-46f5-be18-0095852d1b10.mov

**Comment by shcheklein** [comment]
Thanks! QQ - is there a way to recognize that it was in the "selection mode" and do not activate the action?

**Comment by sroy3** [comment]
> Thanks! QQ - is there a way to recognize that it was in the "selection mode" and do not activate the action?

Wasn't easy, but I got it!

https://user-images.githubusercontent.com/3683420/185469462-b38839e8-7bf5-4515-8dd0-443080b02cb3.mov

**Review by julieg18 — APPROVED** [review]

**Review by mattseddon — APPROVED** [review]

**Pull request merged**
